### ISSUE TITLE
Support Github login

### ISSUE THREAD

**Issue by diegohaz** [diegohaz/generator-rest#10]
The same way Facebook login was implemented, we need to:

 - create a `github` service with a `getMe` method in https://github.com/diegohaz/generator-rest/tree/master/generators/app/templates/services

 - create a passport method like https://github.com/diegohaz/generator-rest/blob/master/generators/app/templates/services/passport/index.js#L70-L77

 - and enable the option on https://github.com/diegohaz/generator-rest/blob/master/generators/app/index.js#L51

It's important to note that the API will only handle the token provided by Github and not the entire OAuth process (it must be done on the client).

This issue is participating on the [Digital Ocean's Hacktoberfest](https://hacktoberfest.digitalocean.com/).

**Comment by QzSG** [comment]
@diegohaz Github api will not return email address for a user even with oauth token and user scope if the user does not set his email as show to public

**Comment by diegohaz** [comment]
@QzSG Thank you for the info, I didn't know that. In this case, I think the better solution would be returning a random unique email from `github.getMe()`, as it serves as a translator method. Something like `username@randomcharacters.com`, as well as password is generated here: https://github.com/diegohaz/generator-rest/blob/master/generators/app/templates/api/user/user.model.js#L128

What do you think?

**Comment by QzSG** [comment]
@QzSG Hmm, I would not suggest that due to years of playing around with random email address and accidentally sending many "test" emails to one that apparently was used by someone haha.

I found out that if the Oauth token was generated with the scope `user:email`, the email of the authenticated account can be retrieved from \user\emails. I will bluebird as a dependency to do parallel requests. One to \user and one to \user\emails, hopefully I can send a pr by tonight as this is the first time I am contributing to a generator haha.

**Comment by QzSG** [comment]
in addition, will the following warnings affect testing? I am using win 10 
```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
```

**Comment by QzSG** [comment]
Tasks for me to do 
- [ ] Create a github service with a getMe method in https://github.com/diegohaz/generator-rest/tree/master/generators/app/templates/services

- [ ] Create a passport method like https://github.com/diegohaz/generator-rest/blob/master/generators/app/templates/services/passport/index.js#L70-L77

- [ ] Enable the option on https://github.com/diegohaz/generator-rest/blob/master/generators/app/index.js#L51

**Comment by diegohaz** [comment]
These warnings don't seem to be a problem. The filesystem operations will just perform slower on non MacOS systems. I haven't tested Yeoman on Windows yet, but it should be fine. Please tell me if you find any issue.

**Comment by diegohaz** [comment]
I'm playing around with Windows and I've found some problems I described on #11 
Maybe you come across this.

**Comment by QzSG** [comment]
@diegohaz Finally completed the first part of the task, sorry for the delay. I have tried `yo rest` using the official npm package and it seems to be working (have not tried running the server though), things got delayed due to some other personal commitments, will continue on this and update whenever there is progress. 

With regards to the testing issue, I can foresee how that is going to be a problem to make sure my code does not break things on your side. 

Going to take this one small step at a time, this feature should not break the other parts as its modular, the only affected file might be the passport file.

With regards to testing the github service, the inital requests pulls in a huge number of fields like followed, do u want me to include all the fields in the nock user object?
```
{
  "login": "url",
  "id": url,
  "avatar_url": "url",
  "gravatar_id": "",
  "url": "https://api.github.com/users/QzSG",
  "html_url": "https://github.com/QzSG",
  "followers_url": "https://api.github.com/users/QzSG/followers",
  "following_url": "https://api.github.com/users/QzSG/following{/other_user}",
  "gists_url": "https://api.github.com/users/QzSG/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/QzSG/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/QzSG/subscriptions",
  "organizations_url": "https://api.github.com/users/QzSG/orgs",
  "repos_url": "https://api.github.com/users/QzSG/repos",
  "events_url": "https://api.github.com/users/QzSG/events{/privacy}",
  "received_events_url": "https://api.github.com/users/QzSG/received_events",
  "type": "User",
  "site_admin": false,
  "name": null,
  "company": null,
  "blog": null,
  "location": "0",
  "email": null,
  "hireable": null,
  "bio": "0",
  "public_repos": 0,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "**",
  "updated_at": "**",
  "private_gists": 0,
  "total_private_repos": 0,
  "owned_private_repos": 0,
  "disk_usage": 9999,
  "collaborators": 0,
  "plan": {
    "name": "**",
    "space": 9999999,
    "collaborators": 0,
    "private_repos": 9999
  }
}
```

**Comment by diegohaz** [comment]
I think I've solved #11 with in https://github.com/diegohaz/generator-rest/commit/d69c0571b7eb37a1b0266c30d846b90eb67d0cee 

But I'm having trouble to set up the environment on Windows (specifically adding .NET Frameworks for node-gyp to run) to see if it's actually working.

About your question, you can put all fields on nock, because someone may want to extract another data from github.

**Comment by QzSG** [comment]
@diegohaz 

With regards to 

> create a passport method like https://github.com/diegohaz/generator-rest/blob/master/generators/app/templates/services/passport/index.js#L70-L77

Would it be better for me to add all relevant lines just like the facebook related lines that contains
`authMethods.indexOf('facebook')`?

I might have to continue this tomorrow morning, so if I do not reply to any other comments do not be worried, I will finish it asap tomorrow.

**Comment by QzSG** [comment]
@diegohaz This task is more or less done except for the test for the passport method not added yet
Refer to tasklist : https://github.com/diegohaz/generator-rest/issues/10#issuecomment-250910132

If you have time while I am offline , feel free to clone https://github.com/QzSG/generator-rest which contain my comits. Since I would be unable to test it properly for now. I will add the tests for the passport method first thing tomorrow. 😄

**Comment by diegohaz** [comment]
Thank you very much @QzSG. 

I wrote a review for your PR. 

You don't need to test the passport method because the passport package is already tested and we have tests for `User.createFromService`. We also have integration tests that test all these things together (`POST /auth/github`): https://github.com/diegohaz/generator-rest/blob/fix/windows-scripts/generators/app/templates/api/auth/auth.router.test.js#L115-L141
