### ISSUE TITLE
Add an option to enable paginated retrieval of resource lists

### ISSUE THREAD

**Issue by jay-at-avido** [diegohaz/generator-rest#24]
Maybe leverage something like this:
[https://www.npmjs.com/package/mongoose-paginate](https://www.npmjs.com/package/mongoose-paginate)

**Comment by diegohaz** [comment]
The `GET /resources` routes already support pagination through [this library](https://github.com/diegohaz/querymen).

You can just call `GET /resources?page=2&limit=20` and it should work.

I personally don't like `mongoose-paginate`. It has some performance issues and lacks integration with query strings.

Take a look at querymen and see if it fits your needs. Otherwise you can open an issue there so we can improve the library. :)
